### ISSUE TITLE
python3: can't open file 'install': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hakimarx** [MA24th/WiFiHunter#1]
a@kali:~$ git clone https://github.com/MA24th/WiFiHunter.git
Cloning into 'WiFiHunter'...
remote: Enumerating objects: 407, done.
remote: Counting objects: 100% (407/407), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 407 (delta 242), reused 382 (delta 224), pack-reused 0
Receiving objects: 100% (407/407), 151.87 KiB | 299.00 KiB/s, done.
Resolving deltas: 100% (242/242), done.
a@kali:~$ cd WiFiHunter
a@kali:~/WiFiHunter$ sudo python3 install setup.py
python3: can't open file 'install': [Errno 2] No such file or directory
a@kali:~/WiFiHunter$ ls
bin  LICENSE  README.md  README.rst  run.py  setup.cfg  setup.py  src  tests  wordlist-top4800-probable.txt
a@kali:~/WiFiHunter$ sudo python3 install setup.py
python3: can't open file 'install': [Errno 2] No such file or directory
a@kali:~/WiFiHunter$

**Comment by MA24th** [comment]
Use 
```bash
sudo python3 setup.py install
```
